/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SuperDatepicker {
    /**
    * Selected date Note: Shouldn't be used with `range`. If both `range` and `date` are set, `range` will be prioritized.
    */
    'date': string | Date | number;
  }
}

declare global {


  interface HTMLSuperDatepickerElement extends Components.SuperDatepicker, HTMLStencilElement {}
  var HTMLSuperDatepickerElement: {
    prototype: HTMLSuperDatepickerElement;
    new (): HTMLSuperDatepickerElement;
  };
  interface HTMLElementTagNameMap {
    'super-datepicker': HTMLSuperDatepickerElement;
  }
}

declare namespace LocalJSX {
  interface SuperDatepicker {
    /**
    * Selected date Note: Shouldn't be used with `range`. If both `range` and `date` are set, `range` will be prioritized.
    */
    'date'?: string | Date | number;
  }

  interface IntrinsicElements {
    'super-datepicker': SuperDatepicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'super-datepicker': LocalJSX.SuperDatepicker & JSXBase.HTMLAttributes<HTMLSuperDatepickerElement>;
    }
  }
}


