/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DatepickerButton {
    /**
    * Whether the button is an icon button
    */
    'iconOnly': boolean;
  }
  interface SuperDatepicker {
    /**
    * Selected date Note: Shouldn't be used with `range`. If both `range` and `date` are set, `range` will be prioritized.
    */
    'date': string | Date | number;
    'view': 'date' | 'month' | 'year';
  }
}

declare global {


  interface HTMLDatepickerButtonElement extends Components.DatepickerButton, HTMLStencilElement {}
  var HTMLDatepickerButtonElement: {
    prototype: HTMLDatepickerButtonElement;
    new (): HTMLDatepickerButtonElement;
  };

  interface HTMLSuperDatepickerElement extends Components.SuperDatepicker, HTMLStencilElement {}
  var HTMLSuperDatepickerElement: {
    prototype: HTMLSuperDatepickerElement;
    new (): HTMLSuperDatepickerElement;
  };
  interface HTMLElementTagNameMap {
    'datepicker-button': HTMLDatepickerButtonElement;
    'super-datepicker': HTMLSuperDatepickerElement;
  }
}

declare namespace LocalJSX {
  interface DatepickerButton {
    /**
    * Whether the button is an icon button
    */
    'iconOnly'?: boolean;
  }
  interface SuperDatepicker {
    /**
    * Selected date Note: Shouldn't be used with `range`. If both `range` and `date` are set, `range` will be prioritized.
    */
    'date'?: string | Date | number;
    'view'?: 'date' | 'month' | 'year';
  }

  interface IntrinsicElements {
    'datepicker-button': DatepickerButton;
    'super-datepicker': SuperDatepicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'datepicker-button': LocalJSX.DatepickerButton & JSXBase.HTMLAttributes<HTMLDatepickerButtonElement>;
      'super-datepicker': LocalJSX.SuperDatepicker & JSXBase.HTMLAttributes<HTMLSuperDatepickerElement>;
    }
  }
}


